name: mypy type check

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: jpetrucciani/mypy-check@master
        with:
          mypy_flags: '--config-file pyproject.toml'
          requirements_file: 'requirements_all.txt'
